(define (problem driverlog-problem)
  (:domain driverlog)
  
  (:objects 
    driver1 driver2 driver3 driver4 driver5 - driver
    truck1 truck2 truck3 truck4 truck5 - truck
    package1 package2 package3 package4 package5 package6 package7 package8 package9 package10 - obj
    s0 s1 s2 s3 s4 s5 s6 s7 s8 s9 s10 s11 s12 s13 s14 - location
  )
  
  (:init 
    (at driver1 s14)
    (at driver2 s1)
    (at driver3 s0)
    (at driver4 s10)
    (at driver5 s12)
    (at truck1 s7)
    (at truck2 s1)
    (at truck3 s2)
    (at truck4 s13)
    (at truck5 s3)
    (empty truck1)
    (empty truck2)
    (empty truck3)
    (empty truck4)
    (empty truck5)
    (in package1 truck1)
    (in package2 truck2)
    (in package3 truck3)
    (in package4 truck4)
    (in package5 truck5)
    (in package6 truck2)
    (in package7 truck3)
    (in package8 truck1)
    (in package9 truck5)
    (in package10 truck1)
  )
  
  (:goal 
    (and (at driver1 s12)
         (at driver2 s11)
         (at driver3 s11)
         (at driver4 s12)
         (at driver5 s11)
         (at truck1 s5)
         (at truck2 s6)
         (at truck3 s8)
         (at truck4 s12)
         (at truck5 s14)
         (at package1 s13)
         (at package2 s0)
         (at package3 s9)
         (at package4 s11)
         (at package5 s9)
         (at package6 s2)
         (at package7 s3)
         (at package8 s6)
         (at package9 s4)
         (at package10 s8)
    )
  )
)